/* Minimal platform configuration used only by the standalone RIX player. */
#ifndef PAL_CONFIG_H
#define PAL_CONFIG_H

#define PAL_PREFIX "./"
#define PAL_SAVE_PREFIX "./"

#define PAL_DEFAULT_WINDOW_WIDTH 760
#define PAL_DEFAULT_WINDOW_HEIGHT 360
#define PAL_DEFAULT_FULLSCREEN_HEIGHT 360
#define PAL_DEFAULT_TEXTURE_WIDTH PAL_DEFAULT_WINDOW_WIDTH
#define PAL_DEFAULT_TEXTURE_HEIGHT PAL_DEFAULT_WINDOW_HEIGHT

#define PAL_VIDEO_INIT_FLAGS SDL_WINDOW_RESIZABLE
#define PAL_SDL_INIT_FLAGS (SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_EVENTS)

#define PAL_PLATFORM "SDLPAL RIX Music Player"
#define PAL_CREDIT "Standalone utility"
#define PAL_PORTYEAR "2026"

#define PAL_HAS_CONFIG_PAGE 0
#define PAL_HAS_NATIVEMIDI 0
#define PAL_HAS_JOYSTICKS 0
#define PAL_HAS_TOUCH 0
#define PAL_HAS_GLSL 0
#define PAL_HAS_SDLCD 0

#endif
